# !!! `db.*` ONLY FOR DEV MODE !!!
db.url: jdbc:mysql://127.0.0.1:3306/rebuild20?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&sessionVariables=default_storage_engine=InnoDB
db.user: rebuild
db.passwd: rebuild
# Use built-in ehcache if redis not defined or unavailable
db.CacheHost: 127.0.0.1
db.CachePort: 6379
db.CachePassword: AES(vXwBKYUosMpJRO9jeG9+IA==)

# REBUILD
rebuild:
  # Cloud Storage - Use https://www.qiniu.com/
  StorageURL: //qn-cdn.getrebuild.com/
  StorageBucket: rb-cdn
  StorageApiKey: AES(zYkDunIsyaZd71rZoW1KPtJPIutYBsBqNaZxpE+4xNl9urgpG+Py0Q0w5m2+Z72e)
  StorageApiSecret: AES(Ke7e7qzT+5F2HC3C/89a5Aq+UopTPHygiSpPfnQjnSrpxgUtiSlauQbPnowtl+ew)
  # SMS - Use https://www.mysubmail.com/
  SmsUser: 30912
  SmsPassword: AES(w07FOXTgIF5vuU2uWOLHhgeBv2dSExddnQQ8f534GXMKxKZT7YVYoWKjP8gPrEIS)
  SmsSign: REBUILD
  # Mail - Use https://www.mysubmail.com/
  MailUser: 14022
  MailPassword: AES(vRnLDh4PVen2faMH+itQuFjzwBcWtCTO6qslkF36VAoKxKZT7YVYoWKjP8gPrEIS)
  MailAddr: hi@smtp.getrebuild.com
  MailName: REBUILD

# TOMCAT (Built-in)
server:
  port: 18080
  servlet:
    context-path: /rebuild
    encoding:
      charset: UTF-8
      force: true
    session:
      tracking-modes: cookie
  error:
    whitelabel.enabled: true
  tomcat:
    uri-encoding: UTF-8
    threads.max: 200

# SPRING
spring:
  mvc:
    static-path-pattern: /assets/**
  resources:
    static-locations: classpath:/web/assets
  servlet:
    multipart.enabled: false
  thymeleaf:
    prefix: classpath:/web
    cache: false
    enable-spring-el-compiler: false
  quartz:
    scheduler-name: rbScheduler
    startup-delay: 15s
