name: Lint

on: [push]

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: cd ./src/main/resources/web
    - run: npm install
    - run: npm run lint
