name: Lint

on: [push]

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm-install
      run: npm install
      working-directory: ./src/main/resources/web
    - name: npm-run-lint
      run: npm run lint
      working-directory: ./src/main/resources/web
